services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Clustering
    command: >
      --jetstream 
      --store_dir=/data
      --http_port=8222
    volumes:
      - ${NATS_DATA_PATH}:/data
    restart: unless-stopped
    networks:
      - nats-network

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    command: "tail -f /dev/null"  # Keep container running
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge